"""MySQL database for NEOwatch Bot.

Split from a single 3,655-line database.py into one module per concern.
This __init__ re-exports every public and private name the old flat module
exposed, so existing call sites (``from database import get_user``, etc.)
keep working unchanged — see CLAUDE.md's "Database" section for the table
list and web/data/ for how the site layer consumes this package.
"""
from .pool import get_db_connection
from .schema import init_db

from .users import (
    QUIET_HOURS_PRESETS,
    ISS_FILTER_PRESETS,
    get_user,
    get_user_lang,
    update_user_lang,
    create_or_update_user,
    update_user_location,
    toggle_subscription,
    cycle_quiet_hours,
    cycle_iss_filter,
    get_iss_subscribers,
    get_apod_subscribers,
    get_launch_subscribers,
    get_neo_subscribers,
    get_news_subscribers,
    get_meteor_subscribers,
    get_flare_subscribers,
    get_grb_subscribers,
    get_gw_subscribers,
    upsert_push_subscription,
    delete_push_subscription,
    get_push_subscriptions,
    update_push_last_iss_pass,
    update_last_iss_pass,
    update_last_apod_date,
    get_last_apod_for_user,
    get_user_count,
    set_subscription,
)

from .geocoding import (
    get_city_suggestions,
    reverse_geocode,
)

from .notifications import (
    is_launch_notified,
    mark_launch_notified,
    cleanup_old_launch_notifications,
    is_neo_notified,
    mark_neo_notified,
    cleanup_old_neo_notifications,
    is_news_notified,
    mark_news_notified,
    cleanup_old_news_notifications,
    is_meteor_notified,
    mark_meteor_notified,
    cleanup_old_meteor_notifications,
    is_flare_notified,
    mark_flare_notified,
    cleanup_old_flare_notifications,
    is_storm_notified,
    mark_storm_notified,
    cleanup_old_storm_notifications,
    is_grb_notified,
    mark_grb_notified,
    cleanup_old_grb_notifications,
    is_gw_notified,
    mark_gw_notified,
    get_recent_gw_alerts,
    cleanup_old_gw_notifications,
)

from .news import (
    normalize_url,
    ingest_news_articles,
    set_news_article_videos,
    update_news_article,
    delete_news_article,
    create_news_article_manual,
    refresh_news_article_from_source,
    get_news_article_videos,
    set_news_article_images,
    get_news_article_images,
    get_news_articles,
    count_news_articles,
    get_news_article,
    get_news_article_by_slug,
    get_related_news_articles,
    set_news_article_body,
)

from .apod import (
    ingest_apod_entries,
    get_apod_entries,
    get_apod_entries_admin,
    count_apod_entries,
    get_apod_entry,
    update_apod_entry,
    delete_apod_entry,
    backfill_apod_archive,
)

from .galaxies import (
    ingest_galaxies,
    ingest_galaxy_photos,
    get_galaxies,
    get_galaxy_photos,
    get_galaxy_photo_counts,
    get_galaxy_by_slug,
    galaxy_key_exists,
    add_galaxy_photo,
    delete_galaxy_photo,
    backfill_galaxies,
)

from .missions import (
    get_mission_previews,
    get_mission_preview,
    set_mission_preview,
    delete_mission_preview,
)

from .web_accounts import (
    create_web_user,
    get_web_user_by_id,
    get_web_user_by_email,
    get_web_user_by_google_id,
    get_web_user_by_telegram_id,
    update_web_user_profile,
    set_web_user_password,
    set_web_user_avatar,
    link_web_user_telegram,
    unlink_web_user_telegram,
    bump_web_user_token_version,
    delete_web_user,
    set_web_user_role,
    list_web_users,
    count_web_users,
    create_saved_location,
    get_saved_locations,
    delete_saved_location,
)

__all__ = [
    "get_db_connection", "init_db",
    "QUIET_HOURS_PRESETS", "ISS_FILTER_PRESETS",
    "get_user", "get_user_lang", "update_user_lang", "create_or_update_user",
    "update_user_location", "toggle_subscription", "cycle_quiet_hours",
    "cycle_iss_filter", "get_iss_subscribers", "get_apod_subscribers",
    "get_launch_subscribers", "get_neo_subscribers", "get_news_subscribers",
    "get_meteor_subscribers", "get_flare_subscribers", "get_grb_subscribers",
    "get_gw_subscribers", "upsert_push_subscription", "delete_push_subscription",
    "get_push_subscriptions", "update_push_last_iss_pass", "update_last_iss_pass",
    "update_last_apod_date", "get_last_apod_for_user", "get_user_count",
    "set_subscription",
    "get_city_suggestions", "reverse_geocode",
    "is_launch_notified", "mark_launch_notified", "cleanup_old_launch_notifications",
    "is_neo_notified", "mark_neo_notified", "cleanup_old_neo_notifications",
    "is_news_notified", "mark_news_notified", "cleanup_old_news_notifications",
    "is_meteor_notified", "mark_meteor_notified", "cleanup_old_meteor_notifications",
    "is_flare_notified", "mark_flare_notified", "cleanup_old_flare_notifications",
    "is_storm_notified", "mark_storm_notified", "cleanup_old_storm_notifications",
    "is_grb_notified", "mark_grb_notified", "cleanup_old_grb_notifications",
    "is_gw_notified", "mark_gw_notified", "get_recent_gw_alerts",
    "cleanup_old_gw_notifications",
    "normalize_url", "ingest_news_articles", "set_news_article_videos",
    "update_news_article", "delete_news_article", "create_news_article_manual",
    "refresh_news_article_from_source", "get_news_article_videos",
    "set_news_article_images", "get_news_article_images", "get_news_articles",
    "count_news_articles", "get_news_article", "get_news_article_by_slug",
    "get_related_news_articles", "set_news_article_body",
    "ingest_apod_entries", "get_apod_entries", "get_apod_entries_admin",
    "count_apod_entries", "get_apod_entry", "update_apod_entry",
    "delete_apod_entry", "backfill_apod_archive",
    "ingest_galaxies", "ingest_galaxy_photos", "get_galaxies", "get_galaxy_photos",
    "get_galaxy_photo_counts", "get_galaxy_by_slug", "galaxy_key_exists",
    "add_galaxy_photo", "delete_galaxy_photo", "backfill_galaxies",
    "get_mission_previews", "get_mission_preview", "set_mission_preview",
    "delete_mission_preview",
    "create_web_user", "get_web_user_by_id", "get_web_user_by_email",
    "get_web_user_by_google_id", "get_web_user_by_telegram_id",
    "update_web_user_profile", "set_web_user_password", "set_web_user_avatar",
    "link_web_user_telegram", "unlink_web_user_telegram",
    "bump_web_user_token_version", "delete_web_user", "set_web_user_role",
    "list_web_users", "count_web_users", "create_saved_location",
    "get_saved_locations", "delete_saved_location",
]
